// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/module.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Content struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac20a1b488b71508, []int{0}
}

func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (m *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(m, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ContentRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContentRequest) Reset()         { *m = ContentRequest{} }
func (m *ContentRequest) String() string { return proto.CompactTextString(m) }
func (*ContentRequest) ProtoMessage()    {}
func (*ContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac20a1b488b71508, []int{1}
}

func (m *ContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentRequest.Unmarshal(m, b)
}
func (m *ContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentRequest.Marshal(b, m, deterministic)
}
func (m *ContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentRequest.Merge(m, src)
}
func (m *ContentRequest) XXX_Size() int {
	return xxx_messageInfo_ContentRequest.Size(m)
}
func (m *ContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContentRequest proto.InternalMessageInfo

func (m *ContentRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ContentResponse struct {
	Contents             []*Content `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ContentResponse) Reset()         { *m = ContentResponse{} }
func (m *ContentResponse) String() string { return proto.CompactTextString(m) }
func (*ContentResponse) ProtoMessage()    {}
func (*ContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac20a1b488b71508, []int{2}
}

func (m *ContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentResponse.Unmarshal(m, b)
}
func (m *ContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentResponse.Marshal(b, m, deterministic)
}
func (m *ContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentResponse.Merge(m, src)
}
func (m *ContentResponse) XXX_Size() int {
	return xxx_messageInfo_ContentResponse.Size(m)
}
func (m *ContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContentResponse proto.InternalMessageInfo

func (m *ContentResponse) GetContents() []*Content {
	if m != nil {
		return m.Contents
	}
	return nil
}

type Metadata struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RootPath             string   `protobuf:"bytes,2,opt,name=rootPath,proto3" json:"rootPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac20a1b488b71508, []int{3}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Metadata) GetRootPath() string {
	if m != nil {
		return m.RootPath
	}
	return ""
}

type MetadataResponse struct {
	Metadata             *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MetadataResponse) Reset()         { *m = MetadataResponse{} }
func (m *MetadataResponse) String() string { return proto.CompactTextString(m) }
func (*MetadataResponse) ProtoMessage()    {}
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac20a1b488b71508, []int{4}
}

func (m *MetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataResponse.Unmarshal(m, b)
}
func (m *MetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataResponse.Marshal(b, m, deterministic)
}
func (m *MetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataResponse.Merge(m, src)
}
func (m *MetadataResponse) XXX_Size() int {
	return xxx_messageInfo_MetadataResponse.Size(m)
}
func (m *MetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataResponse proto.InternalMessageInfo

func (m *MetadataResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type NavigationEntry struct {
	Key                  string             `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Path                 string             `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Subs                 []*NavigationEntry `protobuf:"bytes,3,rep,name=subs,proto3" json:"subs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NavigationEntry) Reset()         { *m = NavigationEntry{} }
func (m *NavigationEntry) String() string { return proto.CompactTextString(m) }
func (*NavigationEntry) ProtoMessage()    {}
func (*NavigationEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac20a1b488b71508, []int{5}
}

func (m *NavigationEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NavigationEntry.Unmarshal(m, b)
}
func (m *NavigationEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NavigationEntry.Marshal(b, m, deterministic)
}
func (m *NavigationEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NavigationEntry.Merge(m, src)
}
func (m *NavigationEntry) XXX_Size() int {
	return xxx_messageInfo_NavigationEntry.Size(m)
}
func (m *NavigationEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_NavigationEntry.DiscardUnknown(m)
}

var xxx_messageInfo_NavigationEntry proto.InternalMessageInfo

func (m *NavigationEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *NavigationEntry) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *NavigationEntry) GetSubs() []*NavigationEntry {
	if m != nil {
		return m.Subs
	}
	return nil
}

type NavigationResponse struct {
	Entries              []*NavigationEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NavigationResponse) Reset()         { *m = NavigationResponse{} }
func (m *NavigationResponse) String() string { return proto.CompactTextString(m) }
func (*NavigationResponse) ProtoMessage()    {}
func (*NavigationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac20a1b488b71508, []int{6}
}

func (m *NavigationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NavigationResponse.Unmarshal(m, b)
}
func (m *NavigationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NavigationResponse.Marshal(b, m, deterministic)
}
func (m *NavigationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NavigationResponse.Merge(m, src)
}
func (m *NavigationResponse) XXX_Size() int {
	return xxx_messageInfo_NavigationResponse.Size(m)
}
func (m *NavigationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NavigationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NavigationResponse proto.InternalMessageInfo

func (m *NavigationResponse) GetEntries() []*NavigationEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac20a1b488b71508, []int{7}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Content)(nil), "proto.Content")
	proto.RegisterType((*ContentRequest)(nil), "proto.ContentRequest")
	proto.RegisterType((*ContentResponse)(nil), "proto.ContentResponse")
	proto.RegisterType((*Metadata)(nil), "proto.Metadata")
	proto.RegisterType((*MetadataResponse)(nil), "proto.MetadataResponse")
	proto.RegisterType((*NavigationEntry)(nil), "proto.NavigationEntry")
	proto.RegisterType((*NavigationResponse)(nil), "proto.NavigationResponse")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ModuleClient is the client API for Module service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModuleClient interface {
	Contents(ctx context.Context, in *ContentRequest, opts ...grpc.CallOption) (*ContentResponse, error)
	Metadata(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MetadataResponse, error)
	Navigation(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NavigationResponse, error)
}

type moduleClient struct {
	cc *grpc.ClientConn
}

func NewModuleClient(cc *grpc.ClientConn) ModuleClient {
	return &moduleClient{cc}
}

func (c *moduleClient) Contents(ctx context.Context, in *ContentRequest, opts ...grpc.CallOption) (*ContentResponse, error) {
	out := new(ContentResponse)
	err := c.cc.Invoke(ctx, "/proto.Module/Contents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleClient) Metadata(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MetadataResponse, error) {
	out := new(MetadataResponse)
	err := c.cc.Invoke(ctx, "/proto.Module/Metadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleClient) Navigation(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NavigationResponse, error) {
	out := new(NavigationResponse)
	err := c.cc.Invoke(ctx, "/proto.Module/Navigation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModuleServer is the server API for Module service.
type ModuleServer interface {
	Contents(context.Context, *ContentRequest) (*ContentResponse, error)
	Metadata(context.Context, *Empty) (*MetadataResponse, error)
	Navigation(context.Context, *Empty) (*NavigationResponse, error)
}

func RegisterModuleServer(s *grpc.Server, srv ModuleServer) {
	s.RegisterService(&_Module_serviceDesc, srv)
}

func _Module_Contents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServer).Contents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Module/Contents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServer).Contents(ctx, req.(*ContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Module_Metadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServer).Metadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Module/Metadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServer).Metadata(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Module_Navigation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServer).Navigation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Module/Navigation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServer).Navigation(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Module_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Module",
	HandlerType: (*ModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Contents",
			Handler:    _Module_Contents_Handler,
		},
		{
			MethodName: "Metadata",
			Handler:    _Module_Metadata_Handler,
		},
		{
			MethodName: "Navigation",
			Handler:    _Module_Navigation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/module.proto",
}

func init() { proto.RegisterFile("pkg/proto/module.proto", fileDescriptor_ac20a1b488b71508) }

var fileDescriptor_ac20a1b488b71508 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x5d, 0x4b, 0xc3, 0x30,
	0x14, 0xa5, 0xfb, 0xac, 0x77, 0x63, 0x1b, 0x01, 0xe7, 0x1c, 0x08, 0x23, 0xf8, 0x30, 0x26, 0x6c,
	0x5a, 0xf1, 0x41, 0x41, 0x7c, 0x90, 0xf9, 0x36, 0x91, 0xfe, 0x83, 0x6c, 0x0b, 0xb3, 0xcc, 0x26,
	0xb5, 0x49, 0x85, 0xfe, 0x28, 0xff, 0xa3, 0xf4, 0x36, 0x49, 0xa5, 0xe2, 0x53, 0x6f, 0xef, 0x3d,
	0xf7, 0x9c, 0x73, 0x4f, 0x60, 0x9c, 0x1c, 0x0f, 0xab, 0x24, 0x95, 0x5a, 0xae, 0x62, 0xb9, 0xcf,
	0x3e, 0xf8, 0x12, 0x7f, 0x48, 0x1b, 0x3f, 0xf4, 0x02, 0xba, 0xcf, 0x52, 0x68, 0x2e, 0x34, 0x21,
	0xd0, 0xda, 0x33, 0xcd, 0x26, 0xde, 0xcc, 0x9b, 0xf7, 0x43, 0xac, 0xe9, 0x25, 0x0c, 0xcc, 0x38,
	0xe4, 0x9f, 0x19, 0x57, 0x88, 0x4a, 0x98, 0x7e, 0x47, 0xd4, 0x49, 0x88, 0x35, 0x7d, 0x84, 0xa1,
	0x43, 0xa9, 0x44, 0x0a, 0xc5, 0xc9, 0x02, 0xfc, 0x5d, 0xd9, 0x52, 0x13, 0x6f, 0xd6, 0x9c, 0xf7,
	0x82, 0x41, 0x29, 0xbc, 0xb4, 0x48, 0x37, 0xa7, 0x0f, 0xe0, 0x6f, 0xb8, 0x66, 0x85, 0x60, 0x41,
	0x2f, 0x58, 0xcc, 0x2d, 0x7d, 0x51, 0x93, 0x29, 0xf8, 0xa9, 0x94, 0xfa, 0xad, 0x90, 0x6d, 0x60,
	0xdf, 0xfd, 0xd3, 0x27, 0x18, 0xd9, 0x5d, 0xa7, 0x7d, 0x05, 0x7e, 0x6c, 0x7a, 0xc8, 0xd3, 0x0b,
	0x86, 0x46, 0xdb, 0x41, 0x1d, 0x80, 0xee, 0x60, 0xf8, 0xca, 0xbe, 0xa2, 0x03, 0xd3, 0x91, 0x14,
	0x6b, 0xa1, 0xd3, 0x9c, 0x8c, 0xa0, 0x79, 0xe4, 0xb9, 0xb1, 0x50, 0x94, 0xee, 0xe8, 0x46, 0x75,
	0x34, 0x59, 0x40, 0x4b, 0x65, 0x5b, 0x35, 0x69, 0xe2, 0x75, 0x63, 0xa3, 0x50, 0xe3, 0x0a, 0x11,
	0x43, 0x5f, 0x80, 0x54, 0x03, 0xe7, 0xf3, 0x1a, 0xba, 0x5c, 0xe8, 0x34, 0xe2, 0x36, 0xa2, 0xff,
	0x48, 0x2c, 0x8c, 0x76, 0xa1, 0xbd, 0x8e, 0x13, 0x9d, 0x07, 0xdf, 0x1e, 0x74, 0x36, 0xf8, 0x9c,
	0xe4, 0x1e, 0x7c, 0x13, 0xa9, 0x22, 0xa7, 0xb5, 0x8c, 0xcb, 0x37, 0x9b, 0x8e, 0xeb, 0x6d, 0x63,
	0xe0, 0xe6, 0x57, 0xf0, 0x7d, 0x83, 0x41, 0xfe, 0xe9, 0x59, 0x3d, 0x30, 0xbb, 0x72, 0x07, 0x50,
	0xb9, 0xab, 0x2d, 0x9d, 0xff, 0xb1, 0x6f, 0xd7, 0xb6, 0x1d, 0x9c, 0xdc, 0xfe, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x51, 0x25, 0x49, 0x52, 0x8e, 0x02, 0x00, 0x00,
}
