// Code generated by protoc-gen-go. DO NOT EDIT.
// source: module.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NavigationEntry struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path                 string           `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Subs                 *NavigationEntry `protobuf:"bytes,3,opt,name=subs,proto3" json:"subs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NavigationEntry) Reset()         { *m = NavigationEntry{} }
func (m *NavigationEntry) String() string { return proto.CompactTextString(m) }
func (*NavigationEntry) ProtoMessage()    {}
func (*NavigationEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7704718fb7daeb, []int{0}
}

func (m *NavigationEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NavigationEntry.Unmarshal(m, b)
}
func (m *NavigationEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NavigationEntry.Marshal(b, m, deterministic)
}
func (m *NavigationEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NavigationEntry.Merge(m, src)
}
func (m *NavigationEntry) XXX_Size() int {
	return xxx_messageInfo_NavigationEntry.Size(m)
}
func (m *NavigationEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_NavigationEntry.DiscardUnknown(m)
}

var xxx_messageInfo_NavigationEntry proto.InternalMessageInfo

func (m *NavigationEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NavigationEntry) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *NavigationEntry) GetSubs() *NavigationEntry {
	if m != nil {
		return m.Subs
	}
	return nil
}

type NavigationResponse struct {
	Entries              []*NavigationEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NavigationResponse) Reset()         { *m = NavigationResponse{} }
func (m *NavigationResponse) String() string { return proto.CompactTextString(m) }
func (*NavigationResponse) ProtoMessage()    {}
func (*NavigationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7704718fb7daeb, []int{1}
}

func (m *NavigationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NavigationResponse.Unmarshal(m, b)
}
func (m *NavigationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NavigationResponse.Marshal(b, m, deterministic)
}
func (m *NavigationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NavigationResponse.Merge(m, src)
}
func (m *NavigationResponse) XXX_Size() int {
	return xxx_messageInfo_NavigationResponse.Size(m)
}
func (m *NavigationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NavigationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NavigationResponse proto.InternalMessageInfo

func (m *NavigationResponse) GetEntries() []*NavigationEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae7704718fb7daeb, []int{2}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*NavigationEntry)(nil), "proto.NavigationEntry")
	proto.RegisterType((*NavigationResponse)(nil), "proto.NavigationResponse")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ModuleClient is the client API for Module service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModuleClient interface {
	Navigation(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NavigationResponse, error)
}

type moduleClient struct {
	cc *grpc.ClientConn
}

func NewModuleClient(cc *grpc.ClientConn) ModuleClient {
	return &moduleClient{cc}
}

func (c *moduleClient) Navigation(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NavigationResponse, error) {
	out := new(NavigationResponse)
	err := c.cc.Invoke(ctx, "/proto.Module/Navigation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModuleServer is the server API for Module service.
type ModuleServer interface {
	Navigation(context.Context, *Empty) (*NavigationResponse, error)
}

func RegisterModuleServer(s *grpc.Server, srv ModuleServer) {
	s.RegisterService(&_Module_serviceDesc, srv)
}

func _Module_Navigation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServer).Navigation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Module/Navigation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServer).Navigation(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Module_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Module",
	HandlerType: (*ModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Navigation",
			Handler:    _Module_Navigation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "module.proto",
}

func init() { proto.RegisterFile("module.proto", fileDescriptor_ae7704718fb7daeb) }

var fileDescriptor_ae7704718fb7daeb = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcd, 0x4f, 0x29,
	0xcd, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xa9, 0x5c, 0xfc,
	0x7e, 0x89, 0x65, 0x99, 0xe9, 0x89, 0x25, 0x99, 0xf9, 0x79, 0xae, 0x79, 0x25, 0x45, 0x95, 0x42,
	0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0x36,
	0x48, 0xac, 0x20, 0xb1, 0x24, 0x43, 0x82, 0x09, 0x22, 0x06, 0x62, 0x0b, 0x69, 0x71, 0xb1, 0x14,
	0x97, 0x26, 0x15, 0x4b, 0x30, 0x2b, 0x30, 0x6a, 0x70, 0x1b, 0x89, 0x41, 0xcc, 0xd5, 0x43, 0x33,
	0x2d, 0x08, 0xac, 0x46, 0xc9, 0x8d, 0x4b, 0x08, 0x21, 0x11, 0x94, 0x5a, 0x5c, 0x90, 0x9f, 0x57,
	0x9c, 0x2a, 0x64, 0xc0, 0xc5, 0x9e, 0x9a, 0x57, 0x52, 0x94, 0x99, 0x5a, 0x2c, 0xc1, 0xa8, 0xc0,
	0x8c, 0xc7, 0x10, 0x98, 0x32, 0x25, 0x76, 0x2e, 0x56, 0xd7, 0xdc, 0x82, 0x92, 0x4a, 0x23, 0x7b,
	0x2e, 0x36, 0x5f, 0xb0, 0x77, 0x84, 0x4c, 0xb9, 0xb8, 0x10, 0xca, 0x85, 0x78, 0xa0, 0x26, 0x80,
	0x55, 0x49, 0x49, 0x62, 0x98, 0x07, 0xb3, 0x3b, 0x89, 0x0d, 0x2c, 0x63, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x69, 0xed, 0x63, 0x33, 0x16, 0x01, 0x00, 0x00,
}
